# Global settings cho toàn bộ ứng dụng
# File này sẽ được load cho tất cả environments

# Cấu hình ứng dụng chung
app:
  name: "Ruby on Rails Tutorial Sample App"
  version: "1.0.0"
  description: "Sample application for Rails Tutorial"

# Cấu hình i18n
i18n:
  default_locale: "en"
  available_locales: ["en", "vi"]
  fallback_locale: "en"

# Cấu hình pagination
pagination:
  default_per_page: 10
  max_per_page: 100

# Cấu hình session
session:
  remember_me_value: "1"
  remember_token_expires: 2592000 # 30 days in seconds

# Cấu hình email
email:
  from_address: "noreply@railstutorial.org"
  support_address: "support@railstutorial.org"

# Cấu hình alert classes
alert:
  success: "alert-success"
  error: "alert-danger"
  danger: "alert-danger"
  warning: "alert-warning"
  info: "alert-info"

# Cấu hình colors cho UI
colors:
  primary: "#007bff"
  secondary: "#6c757d"
  success: "#28a745"
  danger: "#dc3545"
  warning: "#ffc107"
  info: "#17a2b8"
  light: "#f8f9fa"
  dark: "#343a40"
  white: "#ffffff"
  border: "#e0e0e0"
  text: "#333333"
  text_muted: "#666666"

# Cấu hình social links
social:
  twitter: "https://twitter.com/railstutorial"
  facebook: "https://facebook.com/railstutorial"
  github: "https://github.com/railstutorial"

# Cấu hình URLs
urls:
  tutorial: "https://www.railstutorial.org/"
  author: "https://www.michaelhartl.com/"
  contact: "https://www.railstutorial.org/contact"
  help: "http://www.railstutorial.org/help"
  book: "http://www.railstutorial.org/book"
  news: "https://news.railstutorial.org/"
  gravatar: "https://secure.gravatar.com/avatar/"
  rails: "https://rubyonrails.org/"

# Cấu hình cache
cache:
  expires_in: 3600 # seconds (1 hour)

# Cấu hình business logic
business:
  # Product stock thresholds
  low_stock_threshold: 10
  # Validation limits
  max_name_length: 255
  max_slug_length: 255
  max_sku_length: 100
  max_description_length: 1000
  # Product display limits
  featured_products_limit: 8
  related_products_limit: 4
  # Auto-generation settings
  sku_prefix_length: 3
  sku_counter_padding: 4
  default_sku_prefix: "PRD"

# Cấu hình image handling
images:
  thumbnail_size: [100, 100]
  medium_size: [300, 300]
  large_size: [800, 600]
  placeholder:
    card_height: "200px"
    detail_height: "400px"

# Cấu hình admin UI
admin:
  categories_display_limit: 2
  dashboard_categories_limit: 8
  recent_products_limit: 5
  low_stock_products_limit: 5
  category_products_limit: 10
  table:
    checkbox_width: "40"
    name_width: "30%"
    action_column_width: "120"

# Cấu hình date formats
date_formats:
  admin_display: "%B %d, %Y"
  admin_display_with_time: "%B %d, %Y at %I:%M %p"
  short_date: "%m/%d/%Y"
  long_date: "%A, %B %d, %Y"

# Cấu hình currency
currency:
  symbol: "$"
  code: "USD"
  position: "before" # before hoặc after
  format:
    unit: ""
    delimiter: ","
    precision: 2
    format: "%n ₫"

# Cấu hình shipping
shipping:
  fees:
    standard: 30000 # 30k VND
    express: 50000 # 50k VND
    same_day: 80000 # 80k VND
  default_method: "standard"

# Cấu hình order
order:
  number:
    prefix: "ORD"
    date_format: "%Y%m%d"
    random_length: 4

# Cấu hình validation
validation:
  phone:
    cleanup_pattern: "[\\s\\-()]"
    vietnam_pattern: "\\A(\\+84|84|0[3|5|7|8|9])+([0-9]{8,9})\\z"
